import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { Icon, type IconName } from './icons';

export function PageHeader({ eyebrow, title, description, action }: { action?: ReactNode; description: string; eyebrow?: string; title: string }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow ? <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--primary)]">{eyebrow}</p> : null}<h1 className="mt-1 text-2xl font-semibold tracking-tight text-[var(--foreground)] sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted-foreground)]">{description}</p></div>{action ? <div className="shrink-0">{action}</div> : null}</div>; }
export function DashboardCard({ children, className = '' }: { children?: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-[var(--border)] bg-[var(--card)] text-[var(--card-foreground)] shadow-[0_14px_35px_rgb(8_13_29_/_0.06)] backdrop-blur-xl ${className}`}>{children}</section>; }
export function SectionHeader({ title, description, action }: { action?: ReactNode; description?: string; title: string }) { return <div className="flex items-start justify-between gap-4"><div><h2 className="text-base font-semibold tracking-tight text-[var(--card-foreground)]">{title}</h2>{description ? <p className="mt-1 text-sm text-[var(--muted-foreground)]">{description}</p> : null}</div>{action ? <div className="shrink-0">{action}</div> : null}</div>; }
export function StatCard({ label, value, detail, icon, tone = 'neutral' }: { detail: string; icon?: IconName; label: string; tone?: 'neutral' | 'positive' | 'warning'; value: string }) { const toneClasses = { neutral: 'bg-[var(--muted)] text-[var(--muted-foreground)]', positive: 'bg-[var(--success-muted)] text-[var(--success)]', warning: 'bg-[var(--warning-muted)] text-[var(--warning)]' }; return <DashboardCard className="group relative overflow-hidden p-5 transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_40px_rgb(8_13_29_/_0.12)] sm:p-6"><span className="absolute -right-8 -top-8 size-28 rounded-full bg-[var(--primary)] opacity-[.07] blur-2xl" /><div className="relative flex items-start justify-between gap-3"><p className="text-sm font-medium text-[var(--muted-foreground)]">{label}</p>{icon ? <span className={`flex size-10 items-center justify-center rounded-2xl ${toneClasses[tone]}`}><Icon name={icon} className="size-4" /></span> : null}</div><p className="relative mt-5 text-2xl font-semibold tracking-tight text-[var(--card-foreground)] tabular-nums sm:text-3xl">{value}</p><span className={`relative mt-4 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${toneClasses[tone]}`}>{detail}</span></DashboardCard>; }
export function EmptyState({ icon, title, description, action }: { action?: ReactNode; description: string; icon: IconName; title: string }) { return <div className="flex min-h-48 flex-col items-center justify-center rounded-xl border border-dashed bg-[var(--muted)]/50 px-5 py-8 text-center"><span className="flex size-10 items-center justify-center rounded-xl bg-[var(--card)] text-[var(--muted-foreground)] shadow-sm"><Icon name={icon} className="size-5" /></span><h3 className="mt-4 text-sm font-semibold text-[var(--card-foreground)]">{title}</h3><p className="mt-1 max-w-sm text-sm leading-6 text-[var(--muted-foreground)]">{description}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
export function ErrorState({ title = 'Bir şeyler ters gitti', description, onRetry }: { description: string; onRetry?: () => void; title?: string }) { return <DashboardCard className="p-6"><p className="font-semibold text-[var(--card-foreground)]">{title}</p><p className="mt-1 text-sm text-[var(--muted-foreground)]">{description}</p>{onRetry ? <button type="button" onClick={onRetry} className="mt-4 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--primary-foreground)]">Tekrar dene</button> : null}</DashboardCard>; }
export function Avatar({ name, className = '' }: { className?: string; name?: string | null }) { const initials = (name ?? 'MoneyPilot').trim().split(/\s+/).slice(0, 2).map((part) => part.charAt(0).toUpperCase()).join(''); return <span className={`inline-flex size-9 shrink-0 items-center justify-center rounded-full bg-[var(--primary)] text-xs font-semibold text-[var(--primary-foreground)] ${className}`}>{initials}</span>; }
export function IconButton({ children, label, className = '', type = 'button', ...properties }: ButtonHTMLAttributes<HTMLButtonElement> & { children: ReactNode; label: string }) { return <button type={type} aria-label={label} className={`inline-flex size-10 items-center justify-center rounded-xl text-[var(--muted-foreground)] hover:bg-[var(--muted)] hover:text-[var(--foreground)] disabled:pointer-events-none disabled:opacity-50 ${className}`} {...properties}>{children}</button>; }
export function Button({ children, className = '', variant = 'primary', ...properties }: ButtonHTMLAttributes<HTMLButtonElement> & { children: ReactNode; variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) { const variants = { primary: 'bg-[linear-gradient(135deg,var(--primary),#987bff)] text-[var(--primary-foreground)] shadow-[0_8px_20px_var(--glow)] hover:-translate-y-0.5', secondary: 'border bg-[var(--secondary)] text-[var(--secondary-foreground)] hover:bg-[var(--muted)]', ghost: 'text-[var(--muted-foreground)] hover:bg-[var(--muted)] hover:text-[var(--foreground)]', danger: 'bg-[var(--destructive)] text-[var(--destructive-foreground)]' }; return <button className={`inline-flex min-h-10 items-center justify-center rounded-xl px-4 py-2.5 text-sm font-semibold disabled:pointer-events-none disabled:opacity-50 ${variants[variant]} ${className}`} {...properties}>{children}</button>; }
export function StatusBadge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' }) { const tones = { neutral: 'bg-[var(--muted)] text-[var(--muted-foreground)]', success: 'bg-[var(--success-muted)] text-[var(--success)]', warning: 'bg-[var(--warning-muted)] text-[var(--warning)]', danger: 'bg-[color-mix(in_srgb,var(--destructive)_12%,var(--card))] text-[var(--destructive)]' }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>; }
export function SkeletonCard() { return <div aria-hidden="true" className="animate-pulse rounded-2xl border bg-[var(--card)] p-6"><div className="h-4 w-24 rounded bg-[var(--muted)]" /><div className="mt-4 h-8 w-32 rounded bg-[var(--muted)]" /><div className="mt-5 h-5 w-20 rounded-full bg-[var(--muted)]" /></div>; }
