'use client';

import { type FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import { isAxiosError } from 'axios';
import { DashboardCard, PageHeader, SectionHeader } from '@/features/dashboard/components/ui';
import { useAuth } from '@/features/auth/auth-context';
import { changePassword, deleteAccount, downloadExport, getSessions, logoutAll, revokeSession, updatePreferences, updateProfile } from '@/features/auth/auth.api';
import { type Currency, type PreferencesRequest } from '@/features/auth/auth.types';
import { type Theme, useTheme } from '@/features/theme/theme-provider';

const input = 'mt-1.5 h-11 w-full rounded-xl border bg-[var(--background)] px-3 text-sm outline-none focus:border-[var(--primary)] focus:ring-4 focus:ring-[var(--secondary)]';
const button = 'rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-[var(--primary-foreground)] disabled:opacity-60';
const themes: { value: Theme; label: string; description: string }[] = [{ value: 'light', label: 'Açık', description: 'Her zaman açık görünüm' }, { value: 'dark', label: 'Koyu', description: 'Her zaman koyu görünüm' }, { value: 'system', label: 'Sistem', description: 'Cihaz ayarını takip eder' }];

function errorMessage(error: unknown): string { if (isAxiosError<{ message?: string | string[] }>(error)) { const message = error.response?.data.message; return Array.isArray(message) ? message[0] ?? 'İşlem tamamlanamadı.' : message ?? 'İşlem tamamlanamadı.'; } return 'İşlem tamamlanamadı. Lütfen tekrar deneyin.'; }

export default function SettingsPage() {
  const { user, loadCurrentUser, logout } = useAuth(); const router = useRouter(); const client = useQueryClient(); const { theme, setTheme } = useTheme();
  const [profile, setProfile] = useState({ name: user?.name ?? '', email: user?.email ?? '', currentPassword: '' });
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmation: '' }); const [notice, setNotice] = useState<string | null>(null); const [dangerPassword, setDangerPassword] = useState(''); const [deleteWord, setDeleteWord] = useState('');
  const sessions = useQuery({ queryKey: ['auth', 'sessions'], queryFn: getSessions });
  const profileMutation = useMutation({ mutationFn: updateProfile, onSuccess: async () => { await loadCurrentUser(); setProfile((p) => ({ ...p, currentPassword: '' })); setNotice('Hesap bilgileriniz kaydedildi.'); } });
  const preferenceMutation = useMutation({ mutationFn: updatePreferences, onSuccess: async () => { await loadCurrentUser(); setNotice('Tercihleriniz kaydedildi.'); } });
  const passwordMutation = useMutation({ mutationFn: changePassword, onSuccess: () => { setPassword({ currentPassword: '', newPassword: '', confirmation: '' }); setNotice('Şifreniz değiştirildi.'); } });
  const revokeMutation = useMutation({ mutationFn: revokeSession, onSuccess: async (_data, id) => { await client.invalidateQueries({ queryKey: ['auth', 'sessions'] }); if (sessions.data?.find((s) => s.id === id)?.current) { await logout(); router.replace('/login'); } } });
  const prefs = user;
  async function submitProfile(event: FormEvent) { event.preventDefault(); setNotice(null); try { await profileMutation.mutateAsync({ name: profile.name, email: profile.email, ...(profile.email !== user?.email ? { currentPassword: profile.currentPassword } : {}) }); } catch (e) { setNotice(errorMessage(e)); } }
  async function submitPassword(event: FormEvent) { event.preventDefault(); setNotice(null); if (password.newPassword !== password.confirmation) { setNotice('Yeni şifreler eşleşmiyor.'); return; } try { await passwordMutation.mutateAsync({ currentPassword: password.currentPassword, newPassword: password.newPassword }); } catch (e) { setNotice(errorMessage(e)); } }
  async function savePreferences(change: PreferencesRequest) { setNotice(null); try { await preferenceMutation.mutateAsync(change); } catch (e) { setNotice(errorMessage(e)); } }
  async function endAll() { if (!window.confirm('Tüm oturumlar sonlandırılsın mı? Bu cihazdan da çıkış yapılacak.')) return; try { await logoutAll(); await logout(); router.replace('/login'); } catch (e) { setNotice(errorMessage(e)); } }
  async function removeAccount(event: FormEvent) { event.preventDefault(); if (deleteWord !== 'SİL') { setNotice('Onay için SİL yazın.'); return; } if (!window.confirm('Hesabınız ve tüm finansal verileriniz kalıcı olarak silinecek. Devam edilsin mi?')) return; try { await deleteAccount(dangerPassword); await logout(); router.replace('/login'); } catch (e) { setNotice(errorMessage(e)); } }
  return <div className="space-y-7"><PageHeader eyebrow="Tercihler" title="Ayarlar" description="Hesabınızı, tercihlerinizi ve verilerinizi tek yerden yönetin." />
    {notice ? <p role="status" className="rounded-xl border px-4 py-3 text-sm">{notice}</p> : null}
    <div className="grid gap-6 xl:grid-cols-2"><div className="space-y-6">
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Hesap" description="Adınızı güncelleyin. E-posta değişiminde mevcut şifreniz gerekir." /><form onSubmit={(e) => void submitProfile(e)} className="mt-5 space-y-4"><Field label="Adınız"><input required minLength={2} value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} className={input} /></Field><Field label="E-posta adresi"><input required type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} className={input} /></Field>{profile.email !== user?.email ? <Field label="Mevcut şifre"><input required type="password" value={profile.currentPassword} onChange={(e) => setProfile({ ...profile, currentPassword: e.target.value })} className={input} /></Field> : null}<button className={button} disabled={profileMutation.isPending}>{profileMutation.isPending ? 'Kaydediliyor…' : 'Hesabı kaydet'}</button></form></DashboardCard>
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Güvenlik" description="Şifrenizi düzenli olarak güncelleyin." /><form onSubmit={(e) => void submitPassword(e)} className="mt-5 space-y-4"><Field label="Mevcut şifre"><input required type="password" value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} className={input} /></Field><Field label="Yeni şifre"><input required minLength={8} maxLength={128} type="password" value={password.newPassword} onChange={(e) => setPassword({ ...password, newPassword: e.target.value })} className={input} /></Field><Field label="Yeni şifre (tekrar)"><input required type="password" value={password.confirmation} onChange={(e) => setPassword({ ...password, confirmation: e.target.value })} className={input} /></Field><button className={button} disabled={passwordMutation.isPending}>Şifreyi değiştir</button></form></DashboardCard>
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Oturumlar" description="Cihaz, IP ve konum bilgisi toplanmaz." action={<button onClick={() => void endAll()} className="text-sm font-semibold text-red-600">Tümünü sonlandır</button>} /><div className="mt-5 space-y-3">{sessions.isLoading ? <p className="text-sm text-[var(--muted-foreground)]">Yükleniyor…</p> : sessions.data?.map((session) => <div key={session.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{session.current ? 'Bu oturum' : 'Etkin oturum'}</p><button onClick={() => { if (window.confirm('Bu oturum sonlandırılsın mı?')) void revokeMutation.mutateAsync(session.id).catch((e) => setNotice(errorMessage(e))); }} className="text-sm font-semibold text-red-600">Sonlandır</button></div><p className="mt-1 text-xs text-[var(--muted-foreground)]">Oluşturulma: {new Date(session.createdAt).toLocaleString('tr-TR')} · Son kullanım: {session.lastUsedAt ? new Date(session.lastUsedAt).toLocaleString('tr-TR') : 'Henüz kullanılmadı'}</p></div>)}</div></DashboardCard>
    </div><div className="space-y-6">
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Tercihler" description="Varsayılan para birimi yalnızca yeni kayıtları etkiler; mevcut kayıtlar dönüştürülmez." /><Field label="Varsayılan para birimi"><select value={prefs?.defaultCurrency ?? 'TRY'} onChange={(e) => void savePreferences({ defaultCurrency: e.target.value as Currency })} className={input}>{(['TRY', 'USD', 'EUR', 'GBP'] as Currency[]).map((currency) => <option key={currency}>{currency}</option>)}</select></Field><div role="radiogroup" className="mt-5 space-y-2">{themes.map((item) => <button key={item.value} type="button" role="radio" aria-checked={theme === item.value} onClick={() => setTheme(item.value)} className={`w-full rounded-xl border p-3 text-left ${theme === item.value ? 'border-[var(--primary)] bg-[var(--secondary)]' : ''}`}><span className="text-sm font-medium">{item.label}</span><span className="block text-xs text-[var(--muted-foreground)]">{item.description}</span></button>)}</div></DashboardCard>
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Bildirimler" description="Bu tercihler ilerideki e-posta/push teslimatları için saklanır; bu sürümde gönderim yapılmaz." /><div className="mt-4 space-y-3">{([{ key: 'budgetAlertsEnabled', label: 'Bütçe uyarıları' }, { key: 'savingsGoalAlertsEnabled', label: 'Birikim hedefi uyarıları' }, { key: 'weeklySummaryEnabled', label: 'Haftalık özet' }] as const).map(({ key, label }) => <label key={key} className="flex items-center justify-between gap-4 rounded-xl border p-3 text-sm font-medium"><span>{label}</span><input type="checkbox" checked={prefs?.[key] ?? false} onChange={(e) => void savePreferences({ [key]: e.target.checked })} /></label>)}</div></DashboardCard>
      <DashboardCard className="p-5 sm:p-6"><SectionHeader title="Verileriniz" description="Yedek indirin veya hesabınızı kalıcı olarak silin." /><div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={() => void downloadExport('json').catch((e) => setNotice(errorMessage(e)))}>JSON indir</button><button className={button} onClick={() => void downloadExport('csv').catch((e) => setNotice(errorMessage(e)))}>CSV ZIP indir</button></div><form onSubmit={(e) => void removeAccount(e)} className="mt-6 border-t pt-5 space-y-3"><p className="text-sm font-semibold text-red-700">Hesabı kalıcı olarak sil</p><Field label="Mevcut şifre"><input required type="password" value={dangerPassword} onChange={(e) => setDangerPassword(e.target.value)} className={input} /></Field><Field label="Onay için SİL yazın"><input required value={deleteWord} onChange={(e) => setDeleteWord(e.target.value)} className={input} /></Field><button className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white">Hesabı sil</button></form></DashboardCard>
    </div></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium"><span>{label}</span>{children}</label>; }
